# Generated by Django 5.1.15 on 2026-09-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, choices=[('pet_name', 'What was the name of your first pet?'), ('birth_city', 'In which city were you born?'), ('school_name', 'What was the name of your first school?'), ('mother_maiden', "What is your mother's maiden name?"), ('favourite_food', 'What is your favourite food?'), ('childhood_friend', 'Who was your best friend growing up?')], max_length=20),
        ),
    ]
