# Generated by Django 5.1.15 on 2026-09-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_settle_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='xp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
