# Generated by Django 5.1.15 on 2026-09-21 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('destination', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('cover_key', models.CharField(default='mountain', max_length=40)),
                ('cover_image', models.URLField(blank=True)),
                ('days', models.PositiveIntegerField(default=1)),
                ('trip_type', models.CharField(default='friends', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('tough', 'Tough')], default='easy', max_length=12)),
                ('best_season', models.CharField(blank=True, max_length=60)),
                ('estimated_cost', models.PositiveIntegerField(default=0)),
                ('route', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL)),
                ('source_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_days', to='explore.track')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('track', 'index')},
            },
        ),
        migrations.CreateModel(
            name='TrackStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(default='sightseeing', max_length=20)),
                ('place_name', models.CharField(blank=True, max_length=160)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('xp_value', models.PositiveIntegerField(default=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('track_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='explore.trackday')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.TextField()),
                ('place', models.CharField(blank=True, max_length=120)),
                ('cover_key', models.CharField(default='mountain', max_length=40)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='explore.track')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='explore.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('track', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TrackSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='explore.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('track', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='explore.travelpost')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
