# Generated by Django 5.1.15 on 2026-09-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackstop',
            name='xp_value',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
