# Generated by Django 5.1.15 on 2026-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_trackstop_xp_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='soundtrack',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
