# Generated by Django 5.1.15 on 2026-09-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_travelpost_soundtrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackstop',
            name='xp_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
