# Generated by Django 5.1.15 on 2026-09-29 05:55

from django.conf import settings
from django.db import migrations, models


def hide_duplicate_tracks(apps, schema_editor):
    """A trip published more than once keeps its first track; the copies are
    hidden (not deleted, so nobody's likes or saves disappear)."""
    Track = apps.get_model("explore", "Track")
    seen = set()
    for track in Track.objects.filter(is_published=True, source_trip__isnull=False).order_by("created_at"):
        key = (track.author_id, track.source_trip_id)
        if key in seen:
            track.is_published = False
            track.save(update_fields=["is_published"])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_decimal_xp'),
        ('trips', '0015_past_trips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(hide_duplicate_tracks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(condition=models.Q(('is_published', True), ('source_trip__isnull', False)), fields=('author', 'source_trip'), name='one_published_track_per_trip'),
        ),
    ]
