# Generated by Django 5.1.15 on 2026-09-22 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explore', '0001_initial'),
        ('trips', '0004_trip_cancelled_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('trip_member_added', 'Added to a trip'), ('trip_joined', 'Someone joined your trip'), ('trip_started', 'Trip started'), ('track_used', 'Someone used your track'), ('new_follower', 'New follower'), ('achievement_unlocked', 'Achievement unlocked')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='explore.track')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='notificatio_user_id_4fcc58_idx')],
            },
        ),
    ]
