# Generated by Django 5.1.15 on 2026-09-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('trip_member_added', 'Added to a trip'), ('trip_joined', 'Someone joined your trip'), ('trip_started', 'Trip started'), ('trip_reminder', 'Trip reminder'), ('activity_reminder', 'Itinerary reminder'), ('track_used', 'Someone used your track'), ('new_follower', 'New follower'), ('achievement_unlocked', 'Achievement unlocked')], max_length=32),
        ),
    ]
