# Generated by Django 5.1.15 on 2026-09-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_expopushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('trip_member_added', 'Added to a trip'), ('trip_joined', 'Someone joined your trip'), ('trip_left', 'Someone left your trip'), ('trip_started', 'Trip started'), ('trip_reminder', 'Trip reminder'), ('activity_reminder', 'Itinerary reminder'), ('trip_cancelled', 'Trip cancelled'), ('trip_completed', 'Trip completed'), ('track_used', 'Someone used your track'), ('track_published', 'Someone you follow published a track'), ('new_follower', 'New follower'), ('achievement_unlocked', 'Achievement unlocked')], max_length=32),
        ),
    ]
