# Generated by Django 5.1.15 on 2026-09-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('trip_member_added', 'Added to a trip'), ('trip_invite', 'Invited to a trip'), ('trip_joined', 'Someone joined your trip'), ('trip_left', 'Someone left your trip'), ('trip_started', 'Trip started'), ('trip_reminder', 'Trip reminder'), ('activity_reminder', 'Itinerary reminder'), ('trip_cancelled', 'Trip cancelled'), ('trip_completed', 'Trip completed'), ('chat_message', 'New message in trip chat'), ('settle_paid', 'Someone says they paid you back'), ('settle_confirmed', 'Your payment was confirmed'), ('xp_released', 'Held XP released after settling up'), ('track_used', 'Someone used your track'), ('track_published', 'Someone you follow published a track'), ('new_follower', 'New follower'), ('achievement_unlocked', 'Achievement unlocked'), ('reward_claimed', 'Someone claimed a reward (admins)'), ('reward_update', 'Your reward claim was handled'), ('past_trip_submitted', 'A past trip is waiting for review (admins)'), ('past_trip_reviewed', 'Your past trip was reviewed'), ('referral_joined', 'Someone joined with your referral link'), ('join_request', 'Someone asked to join your trip'), ('join_request_approved', 'Your request to join a trip was approved'), ('join_request_declined', 'Your request to join a trip was declined')], max_length=32),
        ),
    ]
