# Generated by Django 5.1.15 on 2026-09-28 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_decimal_xp_and_reward_offers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardclaim',
            name='admin_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting for admin'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
    ]
