# Generated by Django 5.1.15 on 2026-09-21 07:15

import django.db.models.deletion
import django.utils.timezone
import trips.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('food', 'Food'), ('travel', 'Travel'), ('stay', 'Stay'), ('adventure', 'Adventure'), ('shopping', 'Shopping'), ('rest', 'Rest'), ('event', 'Event'), ('nature', 'Nature')], default='sightseeing', max_length=20)),
                ('place_name', models.CharField(blank=True, max_length=160)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('xp_value', models.PositiveIntegerField(default=20)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_checkin', models.BooleanField(default=False)),
                ('booking_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_activities', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.day')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['order', 'start_time', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('cover_key', models.CharField(default='mountain', max_length=40)),
                ('cover_image', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trip_type', models.CharField(choices=[('weekend', 'Weekend Getaway'), ('road', 'Road Trip'), ('family', 'Family Trip'), ('friends', 'Friends Trip'), ('couple', 'Couple Trip'), ('solo', 'Solo Trip'), ('college', 'College Group'), ('office', 'Office Trip'), ('pilgrimage', 'Pilgrimage'), ('adventure', 'Adventure / Trek')], default='friends', max_length=20)),
                ('pace', models.CharField(choices=[('relaxed', 'Relaxed'), ('balanced', 'Balanced'), ('packed', 'Packed')], default='balanced', max_length=20)),
                ('transport', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('train', 'Train'), ('flight', 'Flight'), ('bus', 'Bus'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('budget_per_person', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Live'), ('completed', 'Completed')], default='planning', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('join_code', models.CharField(default=trips.models.make_join_code, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='memories/')),
                ('image_url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='trips.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('amount', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('food', 'Food'), ('travel', 'Travel'), ('stay', 'Stay'), ('adventure', 'Adventure'), ('shopping', 'Shopping'), ('rest', 'Rest'), ('event', 'Event'), ('nature', 'Nature')], default='food', max_length=20)),
                ('split_type', models.CharField(choices=[('equal', 'Split equally'), ('payer', 'Paid by one person')], default='equal', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('spent_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
            ],
            options={
                'ordering': ['-spent_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='day',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('packing', 'Packing'), ('documents', 'Documents'), ('booking', 'Bookings'), ('shopping', 'Shopping'), ('other', 'Other')], default='packing', max_length=20)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='trips.trip')),
            ],
            options={
                'ordering': ['is_done', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_messages', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trips.trip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('trip', 'index')},
        ),
        migrations.CreateModel(
            name='TripMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Co-planner'), ('member', 'Traveller')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('trip', 'user')},
            },
        ),
    ]
