# Generated by Django 5.1.15 on 2026-09-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='activity',
            name='place_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='activity',
            name='place_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='area_radius_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
