# Generated by Django 5.1.15 on 2026-09-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_activity_assigned_to_activity_completed_distance_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20),
        ),
    ]
