# Generated by Django 5.1.15 on 2026-09-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hour_before_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='day_before_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
