# Generated by Django 5.1.15 on 2026-09-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_activity_xp_and_experiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripexperience',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tripexperience',
            name='text',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
