# Generated by Django 5.1.15 on 2026-09-24 06:12

import django.db.models.deletion
from django.db import migrations, models


def share_existing(apps, schema_editor):
    """Write-ups made before they were shared to the Feed get their post now."""
    TripExperience = apps.get_model("trips", "TripExperience")
    TravelPost = apps.get_model("explore", "TravelPost")
    for experience in TripExperience.objects.filter(skipped=False, post__isnull=True).select_related("trip"):
        trip = experience.trip
        experience.post = TravelPost.objects.create(
            author_id=experience.user_id,
            trip=trip,
            caption=experience.text,
            place=trip.destination,
            cover_key=trip.cover_key,
            image_url=trip.cover_image,
        )
        experience.save(update_fields=["post"])


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_trackstop_xp_default'),
        ('trips', '0007_tripexperience_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripexperience',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience', to='explore.travelpost'),
        ),
        migrations.RunPython(share_existing, migrations.RunPython.noop),
    ]
