# Generated by Django 5.1.15 on 2026-09-24 12:02

import hashlib

from django.db import migrations, models


def fingerprint_existing(apps, schema_editor):
    """Fingerprint photos uploaded before this, oldest first, so the earliest
    copy of any picture is its original. XP already earned is left alone."""
    Memory = apps.get_model("trips", "Memory")
    seen = set()
    for memory in Memory.objects.order_by("created_at").iterator():
        digest = ""
        if memory.image:
            try:
                h = hashlib.sha256()
                with memory.image.open("rb") as f:
                    for chunk in iter(lambda: f.read(65536), b""):
                        h.update(chunk)
                digest = h.hexdigest()
            except (FileNotFoundError, OSError, ValueError):
                digest = ""  # file gone (e.g. a temporary disk was wiped) — nothing to compare
        elif memory.image_url:
            digest = hashlib.sha256(f"url:{memory.image_url.strip()}".encode()).hexdigest()
        memory.content_hash = digest
        memory.is_original = bool(digest) and digest not in seen
        if digest:
            seen.add(digest)
        memory.save(update_fields=["content_hash", "is_original"])


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_settle_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(fingerprint_existing, migrations.RunPython.noop),
    ]
