# Generated by Django 5.1.15 on 2026-09-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_memory_photo_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmember',
            name='chat_pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripmember',
            name='chat_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
