# Generated by Django 5.1.15 on 2026-09-28 05:27

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Completed trips paid the full completion bonuses (10 XP each) before
    they were recorded per trip, so undo can take back the right amount.
    Planned stops no longer carry a category value — they earn distance XP
    when they're completed."""
    Trip = apps.get_model("trips", "Trip")
    Activity = apps.get_model("trips", "Activity")
    Trip.objects.filter(status="completed").update(completion_bonus=10, organizer_bonus=10)
    Activity.objects.exclude(status="completed").update(xp_value=0)


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_chat_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='leg_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='completion_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trip',
            name='finished_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='organizer_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='xp_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
