# Generated by Django 5.1.15 on 2026-09-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_trip_no_xp_tripinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripexperience',
            name='text',
            field=models.TextField(blank=True, max_length=50000),
        ),
    ]
