# Generated by Django 5.1.15 on 2026-09-29 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_tripexperience_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_past',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='review_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='trip',
            name='review_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Waiting for review'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripexperience',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PastTripConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('min_photos', models.PositiveIntegerField(default=3)),
                ('max_photos', models.PositiveIntegerField(default=30)),
                ('min_stops', models.PositiveIntegerField(default=1)),
                ('require_story', models.BooleanField(default=False)),
                ('min_story_chars', models.PositiveIntegerField(default=10)),
                ('allow_public_story', models.BooleanField(default=True)),
                ('max_age_days', models.PositiveIntegerField(default=3650)),
                ('approval_xp', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('story_xp', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'past trip settings',
                'verbose_name_plural': 'past trip settings',
            },
        ),
    ]
