# Generated by Django 5.1.15 on 2026-09-29 06:03

from django.db import migrations, models


def carry_over_public_trips(apps, schema_editor):
    """Until now a public trip showed on every member's profile — keep that."""
    TripMember = apps.get_model("trips", "TripMember")
    TripMember.objects.filter(trip__is_public=True).update(show_on_map=True)


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_past_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmember',
            name='show_on_map',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(carry_over_public_trips, migrations.RunPython.noop),
    ]
