# Generated by Django 5.1.15 on 2026-09-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_member_show_on_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='open_to_join',
            field=models.BooleanField(default=False),
        ),
    ]
